### ISSUE TITLE
Setup backend project

### ISSUE THREAD

**Issue by sosualfred** [mestafrica/ghana-hazard-reporter#2]
1. Create a folder called `backend`
2. Setup backend project using NodeJs, Express, and MongoDB

**Comment by DanSid** [comment]
Ok Can I take this up

**Comment by EunicePobee** [comment]
I would like to pick this up

**Comment by EunicePobee** [comment]
Thank you @sosualfred

**Comment by sosualfred** [comment]
The time interval confused me. I think @DanSid suggested first, my bad. Please collaborate together.

**Comment by DanSid** [comment]
Ok @sosualfred

**Comment by EunicePobee** [comment]
@sosualfred Please, we have completed the issue and the pull request has been made.

**Comment by sosualfred** [comment]
fixes #4

**Comment by sosualfred** [comment]
fixed by #6
